services:

  mysqldb:
    build: ./mysql
    container_name: sonblogdb
    restart: always
    networks:
      frontend:
        ipv4_address: 172.20.10.6
    environment:
      - MYSQL_DATABASE=son_blog
      - MYSQL_ROOT_PASSWORD=Phani_123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Phani_123
    volumes:
      - ./db_mount:/var/lib/mysql
    ports:
      - "33067:3306"

  sonblog:
    depends_on:
      - mysqldb
    build: ./sonblog
    command: 'python /home/run.py'
    container_name: sonblogapp
    restart: always
    networks:
      frontend:
        ipv4_address: 172.20.10.5
    ports:
      - 5000

  nginx:
    build: ./nginx
    container_name: sonblogweb
    restart: always
    networks:
      frontend:
        ipv4_address: 172.20.10.4
    ports:
      - "80:80"

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.10.0/24
          gateway: 172.20.10.1