apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonblogdb-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/sonblogdb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonblogdb-storageclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi