apiVersion: v1
kind: Service
metadata:
  name: sonblogweb
  labels:
    web: sonblogweb
spec:
  type: LoadBalancer
  selector:
      web: sonblogweb
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80